server:
  port: 8080

flyway:
  cleanOnValidationError: false

spring:
  profile:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/comicsbook_dev
    username: comicsbook
    password: